### ISSUE TITLE
App crashes after running npm run start-dev

### ISSUE THREAD

**Issue by giantthinker** [jurkian/react-bank#2]
I get the following error after running npm run start-dev

> react-bank-api@1.0.0 start-dev /home/abdellah/Desktop/PROJECTS/react-bank/api
> nodemon -r dotenv/config app.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node -r dotenv/config app.js`
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/home/abdellah/Desktop/PROJECTS/react-bank/api/config/config'
Require stack:
- /home/abdellah/Desktop/PROJECTS/react-bank/api/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._resolveFilename (/home/abdellah/Desktop/PROJECTS/react-bank/api/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/abdellah/Desktop/PROJECTS/react-bank/api/app.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/abdellah/Desktop/PROJECTS/react-bank/api/app.js' ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jurkian** [comment]
Right, I forgot about config file.
Now it should be fine.

**Comment by giantthinker** [comment]
Thank you.
